### ISSUE TITLE
AttributeError when trying to use `with ConnectRegistry()`. PyHKEY does not implement __enter__ and __exit__

### ISSUE THREAD

**Issue by yuvalsiev96** [bitranox/fake_winreg#15]
* **I'm submitting a feature request**
  - [ ] bug report
  - [X] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Request a feature: Add `__enter__` and `__exit__` to `fake_winreg.fake_winreg.PyHKEY`
This functionality exists in `winreg`:
```python
with winreg.ConnectRegistry(None, winreg.HKEY_LOCAL_MACHINE) as hive_root:
    # Do stuff
```

* **What is the current behavior?**
```python
hive_root = None
try:
    hive_root = fake_winreg.ConnectRegistry(None, fake_winreg.HKEY_LOCAL_MACHINE)
    # do stuff
finally:
    if hive_root is not None:
        hive_root.Close()
```

* **What is the expected behavior?**
```python
with fake_winreg.ConnectRegistry(None, fake_winreg.HKEY_LOCAL_MACHINE) as hive_root:
    # Do stuff
```
And also:
```python
with fake_winreg.OpenKeyEX(hive_root, "Path\To\Key") as key:
    # Do stuff
```

* **What is the motivation / use case for changing the behavior?**
The motivation to add this functionality is to better mock the `winreg` module.

* **Please tell us about your environment:**

- Module Version : v1.5.6
- Python Version : 3.7
- OS, OS Version : Win10 x64

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow
, gitter, etc)
Currently, When trying to execute the above code with fake_winreg an exception is raised:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-21-13204fe8e48d> in <module>
----> 1 with fake_winreg.ConnectRegistry(None, fake_winreg.HKEY_LOCAL_MACHINE) as hive_root:
      2     pass
      3

AttributeError: __enter__
```

**Comment by bitranox** [comment]
yuvalsie, I would kindly ask You to implement it and make tests, if You are able to.
Or should I take care of it ?
ATM I am a kind of busy with other work, so it might take some time ... 
yours sincerely
Robert

**Comment by bitranox** [comment]
I just relesed Version 1.6.0 on PyPi, so You can use the context manager from now on
